name: Branch CI, PR, and Auto-Merge
on:
  push:
    branches-ignore: ["main"]
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build and test
        run: mvn -q -DskipTests=false test
  create-pr-and-merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "CI: Prepare auto-merge to main"
          title: "Auto-merge: ${{ github.ref_name }} -> main"
          body: "Automated PR created by CI from branch `${{ github.ref_name }}`."
          base: main
          branch: "ci/automerge-${{ github.ref_name }}"
          delete-branch: true
      - name: Enable auto-merge
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify:
    needs: [test, create-pr-and-merge]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: saikadas1998@gmail.com
          password: test_123
          subject: "[Branch CI] ${{ github.repository }} ${{ github.ref_name }} - test:${{ needs.test.result }} pr:${{ needs.create-pr-and-merge.result }}"
          to: saikat.j.das@gmail.com, saikatdasmalda0@gmail.com
          from: saikadas1998@gmail.com
          secure: true
          body: |
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Test status: ${{ needs.test.result }}
            PR/Merge status: ${{ needs.create-pr-and-merge.result }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}